site_name: driganttic
site_description: Ganttic API client
strict: true

theme:
  name: material
  custom_dir: docs/theme
  language: en
  favicon: img/dribia-favicon-120x120.png
  logo: img/logo_dribia_d_blanc.png
repo_name: dribia_team/driganttic
repo_url: https://github.com/Dribia/driganttic
edit_uri:
nav:
  - driganttic: index.md
  - Usage:
    - usage/howto.md
  - Contribute: contribute.md
extra_css:
- stylesheets/extra.css

markdown_extensions:
- pymdownx.tasklist:
    custom_checkbox: true
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- codehilite
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed

