custom_fields:
  task:
    listValues:
      nonBillable: nonBillable
    numbers:
    dates:
  resource:
    listValues:
      Role: role
    numbers:
      Max dedicació facturable: capacity
    dates:
  project:
    listValues:
      Tipus: service
      NoConfirmat: nonConfirmed
    numbers:
      Sprints: sprints
      Lead (%): lds_percent
      Dev (%): dev_percent
      AccMan (%): accman_percent
    dates:
      Data aproximada d'inici: dateAproxStart