custom_fields:
  task:
    listValues:
#    Rol: role
    numbers:
    dates:
  resource:
    listValues:
      Categoria: category
    numbers:
      Max dedicació facturable: capacity
    dates:
  project:
    listValues:
      Tipus: service
      NoConfirmat: nonConfirmed
      AccMan: accMan
    numbers:
      Equip: team
      Sprints: sprints