custom_fields:
  tasks:
    listValues:
      my_custom_ganttic: my_custom_pydantic
    numbers:
      my_custom_ganttic: my_custom_pydantic
    dates:
      my_custom_ganttic: my_custom_pydantic
  projects:
    listValues:
      my_custom_ganttic: my_custom_pydantic
    numbers:
      my_custom_ganttic: my_custom_pydantic
    dates:
      my_custom_ganttic: my_custom_pydantic
  resources:
    listValues:
      my_custom_ganttic: my_custom_pydantic
    numbers:
      my_custom_ganttic: my_custom_pydantic
    dates:
      my_custom_ganttic: my_custom_pydantic
